language: cpp
sudo: required
services:
  - docker

matrix:
    include:
        - os: linux
          compiler: gcc
          env: PPA=beineri/opt-qt57-trusty QT=57
          dist: trusty
        - os: linux
          compiler: clang
          env: QMAKESPEC=linux-clang PPA=beineri/opt-qt57-trusty QT=57
          dist: trusty
        - os: osx


before_install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update           ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo add-apt-repository -y ppa:$PPA ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update -qy ; fi

install:
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew tap homebrew/versions ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install qt55      ; fi
  - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew link qt55 --force ; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -qy qt${QT}base qt${QT}tools cppcheck; fi
  - qmake -version

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source /opt/qt${QT}/bin/qt${QT}-env.sh; fi

script:
  - qmake
  - make

after_script:
  - if [[ "$TRAVIS_OS_NAME" != "osx" ]]; then cppcheck --enable=all -q -Isrc/ `git ls-files src/\*.cpp` ; fi

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/cf558929fabd79e35091
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always

